FROM amazoncorretto:17
LABEL author="nagasuribabukola" organization="techsolutions" project="learning"
COPY spring-petclinic-3.2.0-SNAPSHOT.jar /spring-petclinic-3.2.0.jar
EXPOSE 8080
CMD ["java", "-jar", "spring-petclinic-3.2.0.jar"]